# This file is automatically synchronized from https://github.com/Glatzel/template

name: codecov
description: Upload coverage and test results to Codecov
runs:
  using: composite
  steps:
    - name: Upload coverage to Codecov
      if: ${{ !cancelled() }}
      uses: codecov/codecov-action@e79a6962e0d4c0c17b229090214935d2e33f8354 # v6.0.1
      with:
        verbose: true
    - name: Upload test results to Codecov
      if: ${{ !cancelled() }}
      uses: codecov/codecov-action@e79a6962e0d4c0c17b229090214935d2e33f8354 # v6.0.1
      with:
        report_type: test_results
        fail_ci_if_error: true
        verbose: true
