# This file is automatically synchronized from https://github.com/Glatzel/template

name: codecov
description: Upload coverage and test results to Codecov
runs:
  using: composite
  steps:
    - name: Upload coverage to Codecov
      if: ${{ !cancelled() }}
      uses: codecov/codecov-action@75cd11691c0faa626561e295848008c8a7dddffe # v5.5.4
      with:
        verbose: true
    - name: Upload test results to Codecov
      if: ${{ !cancelled() }}
      uses: codecov/codecov-action@75cd11691c0faa626561e295848008c8a7dddffe # v5.5.4
      with:
        report_type: test_results
        fail_ci_if_error: true
        verbose: true
