# This File is automatically synchronized from https://github.com/Glatzel/template

[workspace]
channels = ["https://prefix.dev/glatzel", "conda-forge"]
platforms = ["linux-64"]

[feature.lefthook.tasks]
lefthook-run = "lefthook run pre-commit --all-files --no-auto-install"

[feature.lefthook.dependencies]
lefthook = "==2.1.10"

[feature.python.dependencies]
numpydoc = "==1.10.0"
python = "3.13.*"
ruff = "==0.15.22"

[feature.rust.dependencies]
cargo-shear = "==1.13.2"

[feature.misc.dependencies]
python = "3.13.*"
actionlint = "==1.7.12"
markdownlint-cli2 = "==0.23.1"
pre-commit-hooks = "==6.0.0"
tombi = "==1.2.2"
typos = "==1.48.0"

[feature.clang.dependencies]
clang-format = "==22.1.8"

[feature.dotnet.dependencies]
dotnet = "==10.0.100"
csharpier = "==1.2.6"

[environments]
lefthook = ["lefthook"]
python = ["python"]
rust = ["rust"]
misc = ["misc"]
clang = ["clang"]
dotnet = ["dotnet"]
