[devop]
vendor = "github"
token = "token_xxxxx"
webhook_secret = "webhook_secret_xxxxxxx"
allowed_repositories = ["self-host-runner"]
allowed_users = ["Glatzel", "foo"]

[runners.ghar-linux-dev-small]
image = "ghcr.io/glatzel/ghar-linux-dev"
count = 2
cpus = 1
memory = 512
volumes = { "/host_dir" = "/target_dir" }
envs = { "FOO" = "BAR" }
secrets = { "SFOO" = ["SBAR", "https://www.google.com/"] }
