# This file is automatically synchronized from https://github.com/Glatzel/template

name: cargo build
description: Build Rust project using cargo

inputs:
  working-directory:
    description: Working directory
    default: .
  options:
    description: Options passed to cargo build
    required: false

runs:
  using: composite
  steps:
    - name: Build project
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: '${{ github.workspace }}/.ci/rust/cargo-build.sh'
      env:
        CARGO_BUILD_OPTIONS: ${{ inputs.options }}
