# This file is automatically synchronized from https://github.com/Glatzel/template

name: cargo build
description: Build Rust project using cargo

inputs:
  working-directory:
    description: Working directory
    default: .
  args:
    description: Additional arguments passed to cargo build
    required: false
    default: --all-features -- -D warnings

runs:
  using: composite
  steps:
    - name: Build project
      shell: pwsh
      working-directory: ${{ inputs.working-directory }}
      run: |
        $ErrorActionPreference = "Stop"
        $PSNativeCommandUseErrorActionPreference = $true

        if (Test-Path ./scripts/setup.ps1) { . ./scripts/setup.ps1 }

        cargo build ${{ inputs.args }}
