[package]
edition.workspace = true
name = "serialport-ext"
version.workspace = true

[dependencies]
clerk = { workspace = true }
serialport = { workspace = true }

[dev-dependencies]
clerk = { workspace = true, features = ["tracing"] }
mischief = { workspace = true }
