# This file is automatically synchronized from https://github.com/Glatzel/template

name: cargo doc
description: Generate Rust documentation using cargo doc

inputs:
  working-directory:
    description: Working directory
    default: .
  args:
    description: Additional arguments passed to cargo doc
    required: false
    default: --all-features --no-deps

runs:
  using: composite
  steps:
    - name: Generate documentation
      shell: pwsh
      working-directory: ${{ inputs.working-directory }}
      run: |
        $ErrorActionPreference = "Stop"
        $PSNativeCommandUseErrorActionPreference = $true

        if (Test-Path ./scripts/setup.ps1) { . ./scripts/setup.ps1 }

        cargo doc ${{ inputs.args }}
      env:
        RUSTDOCFLAGS: "-D warnings"
