# This File is automatically synchronized from https://github.com/Glatzel/template

[workspace]
channels = ["https://prefix.dev/glatzel", "conda-forge"]
platforms = ["linux-64"]

[tasks]
lefthook-run = "lefthook run pre-commit --all-files --no-auto-install"

[dependencies]
actionlint = "==1.7.12"
cargo-machete = "==0.9.1"
lefthook = "==2.1.6"
markdownlint-cli2 = "==0.22.1"
numpydoc = "==1.10.0"
pre-commit-hooks = "==5.0.0"
python = "3.13.*"
ruff = "==0.15.12"
tombi = "==0.11.1"
typos = "==1.46.1"
