mod formatter;
pub mod layer;
pub use fast_setup::init_log_with_level;
pub use formatter::ClerkFormatter;
pub use tracing;
pub use tracing::level_filters::LevelFilter;
mod fast_setup;
mod log_level;
pub use log_level::LogLevel;
mod macros;
