[package]
name = "spek"
version.workspace = true
edition.workspace = true

[dependencies]
generic-num.workspace = true
num-complex.workspace = true
num-traits.workspace = true
phastft = { workspace = true, features = ["complex-nums"], optional = true }
rayon = { workspace = true, optional = true }
rustfft = { workspace = true, optional = true }
thiserror.workspace = true

[dev-dependencies]
insta.workspace = true
mischief.workspace = true
rstest.workspace = true

[features]
parallel = ["rayon", "std"]
std = []

backend-phastft = ["phastft"]
backend-phastft-parallel = ["backend-phastft", "phastft/parallel", "std"]
backend-rustfft = ["rustfft"]
