[package]
name = "spek"
version.workspace = true
edition.workspace = true

[dependencies]
generic-num.workspace = true
num-complex.workspace = true
num-traits.workspace = true
phastft = { workspace = true, features = ["complex-nums"], optional = true }
rayon = { workspace = true, optional = true }
rustfft.workspace = true
thiserror.workspace = true

[dev-dependencies]
insta.workspace = true
mischief.workspace = true
rstest.workspace = true

[features]
parallel = ["phastft/parallel", "rayon", "std"]
std = []
