[package]
name = "spek"
version.workspace = true
edition.workspace = true

[[bench]]
harness = false
name = "fft"

[[bench]]
harness = false
name = "stft"

[dependencies]
generic-num.workspace = true
num-complex = { workspace = true, optional = true }
num-traits.workspace = true
parking_lot.workspace = true
phastft = { workspace = true, optional = true }
rayon = { workspace = true, optional = true }
realfft = { workspace = true, optional = true }
rustfft = { workspace = true, optional = true }
thiserror.workspace = true

[dev-dependencies]
criterion.workspace = true
float-cmp.workspace = true
insta.workspace = true
mischief.workspace = true
rstest.workspace = true

[features]
default = ["default-split"]
default-complex = ["backend-realfft", "backend-rustfft", "complex", "parallel"]
default-split = ["backend-phastft", "backend-phastft-parallel", "parallel", "split"]
parallel = ["rayon", "std"]
std = []

complex = ["num-complex"]
split = []

backend-phastft = ["phastft", "split"]
backend-phastft-parallel = ["backend-phastft", "phastft/parallel", "std"]
backend-realfft = ["complex", "realfft"]
backend-rustfft = ["complex", "rustfft"]
