# This File is automatically synchronized from https://github.com/Glatzel/template

name: cargo miri
description: cargo miri

inputs:
  working-directory:
    description: "working-directory"
    default: .
  args:
    description: "args"
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - run: cargo install cargo-codspeed --locked
      working-directory: ${{ inputs.working-directory }}
      shell: pwsh
    - name: Build the benchmark target(s)
      working-directory: ${{ inputs.working-directory }}
      run: |
        if (Test-Path ./scripts/setup.ps1) { . ./scripts/setup.ps1 }
        cargo codspeed build ${{inputs.args}}
      shell: pwsh
    - name: Run the benchmarks
      uses: CodSpeedHQ/action@v4
      with:
        run: cargo codspeed run
        mode: simulation
        working-directory: ${{ inputs.working-directory }}
