# This file is automatically synchronized from https://github.com/Glatzel/template

name: cargo bench
description: Run Rust benchmarks with CodSpeed

inputs:
  working-directory:
    description: Working directory
    default: .
  options:
    description: Options passed to cargo fuzz test
    required: false

runs:
  using: composite
  steps:
    - name: Build benchmark targets
      run: ${{ github.workspace }}/.ci/rust/cargo-bench.sh
      env:
        CARGO_BENCH_OPTIONS: ${{ inputs.options }}
      working-directory: ${{ inputs.working-directory }}
      shell: bash

    - name: Run benchmarks
      uses: CodSpeedHQ/action@f99becdce5e5d51fd556489ebef684f4ecfd6286 # v4.18.5
      with:
        run: cargo codspeed run
        mode: simulation
        working-directory: ${{ inputs.working-directory }}
