# This file is automatically synchronized from https://github.com/Glatzel/template

name: cargo bench
description: Run Rust benchmarks with CodSpeed

inputs:
  working-directory:
    description: Working directory
    default: .
  args:
    description: Additional arguments passed to cargo codspeed
    required: false
    default: --all-features

runs:
  using: composite
  steps:
    - name: Install cargo-codspeed
      run: pixi global install -c https://prefix.dev/glatzel cargo-codspeed
      shell: pwsh
    - name: Build benchmark targets
      run: |
        if (Test-Path ./scripts/setup.ps1) { . ./scripts/setup.ps1 }
        cargo codspeed build ${{ inputs.args }}
      working-directory: ${{ inputs.working-directory }}
      shell: pwsh
      env:
        RUSTFLAGS: "-D warnings"

    - name: Run benchmarks
      uses: CodSpeedHQ/action@db35df748deb45fdef0960669f57d627c1956c30 # v4.13.1
      with:
        run: cargo codspeed run
        mode: simulation
        working-directory: ${{ inputs.working-directory }}
