# This file is automatically synchronized from https://github.com/Glatzel/template

name: setup rust
description: Set up Rust toolchain with pixi

inputs:
  toolchain:
    description: Rust toolchain to install
    default: stable
    required: false
  components:
    description: Rust components to install
    default: ""
    required: false
  targets:
    description: Rust target to install
    default: ""
    required: false

runs:
  using: composite
  steps:
    - name: Set up pixi
      uses: prefix-dev/setup-pixi@a0af7a228712d6121d37aba47adf55c1332c9c2e # v0.9.4
      with:
        run-install: false

    - name: Install rustup-init (if missing)
      shell: pwsh
      run: |
        if (-not (Get-Command rustup -ErrorAction SilentlyContinue)) {
          pixi global install -c https://prefix.dev/glatzel -c conda-forge rustup-init
        }

    - name: Install Rust toolchain
      shell: pwsh
      run: |
        if (-not (Get-Command rustup -ErrorAction SilentlyContinue)) {
          rustup-init -y --default-toolchain ${{ inputs.toolchain }} --profile minimal
        } else {
          rustup toolchain install ${{ inputs.toolchain }} --profile minimal
          rustup default ${{ inputs.toolchain }}
        }

    - name: Install Rust components
      if: ${{ inputs.components != '' }}
      shell: pwsh
      run: rustup component add ${{ inputs.components }}

    - name: Install Rust targets
      if: ${{ inputs.targets != '' }}
      shell: pwsh
      run: rustup target add ${{ inputs.targets }}