# This file is automatically synchronized from https://github.com/Glatzel/template

name: setup rust
description: Set up Rust toolchain with pixi

inputs:
  toolchain:
    description: Rust toolchain to install
    default: stable
    required: false
  components:
    description: Rust components to install
    required: false
  targets:
    description: Rust target to install
    required: false

runs:
  using: composite
  steps:
    - name: Set up pixi
      uses: prefix-dev/setup-pixi@a09b6247153796b190642a2b53fac4241043cf6f # v0.10.0
      with:
        run-install: false

    - name: Install rust
      shell: bash
      run: |
          ${{ github.workspace }}/.ci/rust/setup-rust.sh
          echo "$HOME/.cargo/bin" >> "$GITHUB_PATH"
      env:
        TOOLCHAIN: ${{ inputs.toolchain }}
        COMPONENTS: ${{ inputs.components }}
        TARGETS: ${{ inputs.targets }}
