[package]
edition.workspace = true
name = "rax-nmea"
version.workspace = true

[dependencies]
chrono = { version = "0.4.41", features = ["serde"] }
clerk = { workspace = true }
miette = "7.6.0"
rax = { workspace = true }
serde = { version = "1.0.219", features = ["derive"] }

[dev-dependencies]
clerk = { workspace = true , features = ["log"]}
criterion = { package = "codspeed-criterion-compat", version = "2.10.1" }
float-cmp = "0.10.0"
serialport = "4.7.2"

[[bench]]
harness = false
name = "nmea"

[[bench]]
harness = false
name = "rules"
