[package]
edition.workspace = true
name = "rax-nmea"
version.workspace = true

[dependencies]
chrono = { workspace = true, features = ["serde"] }
clerk = { workspace = true }
miette = { workspace = true }
rax = { workspace = true }
serde = { workspace = true }

[dev-dependencies]
clerk = { workspace = true , features = ["log"]}
criterion = { workspace = true }
float-cmp = { workspace = true }
serialport = { workspace = true }

[[bench]]
harness = false
name = "nmea"

[[bench]]
harness = false
name = "rules"
