[package]
edition.workspace = true
name = "rax-nmea"
version.workspace = true

[dependencies]
chrono = { version = "0.4.42" ,default-features = false,features = ["clock"]}
clerk = { workspace = true }
rax = { workspace = true }
serde = { version = "1.0.219", features = ["derive"], optional = true }

[dev-dependencies]
mischief = { workspace = true }
clerk = { workspace = true, features = ["log"] }
criterion = { package = "codspeed-criterion-compat", version = "2.10.1" }
float-cmp = "0.10.0"
serialport = "4.7.3"
rax = { workspace = true ,features = ["async"]}

[features]
default = ["std"]
std = ["rax/std"]
serde = ["std", "dep:serde", "chrono/serde"]

[[bench]]
harness = false
name = "nmea"

[[bench]]
harness = false
name = "rules"
