[package]
name = "mischief"
version.workspace = true
edition.workspace = true

[dependencies]
arbor.workspace = true
backtrace = { workspace = true, optional = true }
mischief-macros = { workspace = true, optional = true }
owo-colors = { workspace = true, optional = true }
terminal_size = { workspace = true, optional = true }

[dev-dependencies]
insta = { workspace = true, features = ["filters"] }

[features]
default = ["arbor/default", "backtrace", "fancy", "macros", "std"]
backtrace = ["dep:backtrace", "std", "terminal_size"]
fancy = ["color", "hyperlink", "pretty", "textwrap"]
macros = ["mischief-macros"]
std = []

color = ["owo-colors", "std"]
hyperlink = ["owo-colors", "std"]
pretty = ["owo-colors", "std"]
textwrap = [
  "textwrap-hyphenation",
  "textwrap-smawk",
  "textwrap-unicode-linebreak",
  "textwrap-unicode-width"
]
textwrap-hyphenation = ["arbor/textwrap-hyphenation", "pretty", "std"]
textwrap-smawk = ["arbor/textwrap-smawk", "pretty", "std"]
textwrap-unicode-linebreak = [
  "arbor/textwrap-unicode-linebreak",
  "pretty",
  "std"
]
textwrap-unicode-width = ["arbor/textwrap-unicode-width", "pretty", "std"]
