[package]
edition.workspace = true
name = "mischief"
version.workspace = true

[dependencies]
owo-colors = { workspace = true, optional = true }

[features]
default = ["std"]
fancy = ["owo-colors"]
std = []
