[package]
edition.workspace = true
name = "mischief"
version.workspace = true

[dependencies]
mischief-macros = { workspace = true, optional = true }
owo-colors = { workspace = true, optional = true }
supports-color = { workspace = true, optional = true }
supports-hyperlinks = { workspace = true, optional = true }
supports-unicode = { workspace = true, optional = true }
terminal_size = { workspace = true, optional = true }
textwrap = { workspace = true, optional = true }

[features]
default = ["macros"]
fancy = [
  "owo-colors",
  "textwrap",
  "terminal_size",
  "supports-hyperlinks",
  "supports-color",
  "supports-unicode",
]
macros = ["mischief-macros"]
