[package]
edition.workspace = true
name = "mischief"
version.workspace = true

[dependencies]
owo-colors = { version = "4.2.2", optional = true }
mischief-macros = { workspace = true, optional = true }

[features]
default = ["macros"]
fancy = ["owo-colors"]
macros = ["mischief-macros"]
