[package]
name = "mischief"
version.workspace = true
edition.workspace = true

[dependencies]
arbor.workspace = true
backtrace = { workspace = true, optional = true }
mischief-macros = { workspace = true, optional = true }
owo-colors = { workspace = true, optional = true }
terminal_size = { workspace = true, optional = true }

[dev-dependencies]
insta = { workspace = true, features = ["filters"] }

[features]
default = ["arbor/default", "backtrace", "fancy", "macros", "std"]
backtrace = ["dep:backtrace", "std", "terminal_size"]
fancy = ["color", "hyperlink", "pretty", "textwrap"]
macros = ["mischief-macros"]
std = []

color = ["owo-colors", "std"]
hyperlink = ["owo-colors", "std"]
pretty = ["owo-colors", "std"]

textwrap = [
  "arbor/textwrap",
  "std",
  "terminal_size",
]
textwrap-full = ["arbor/textwrap-full", "std", "terminal_size"]
textwrap-hyphenation = [
  "arbor/textwrap-hyphenation",
  "pretty",
  "std",
  "terminal_size"
]
textwrap-smawk = ["arbor/textwrap-smawk", "pretty", "std", "terminal_size"]
textwrap-unicode-linebreak = [
  "arbor/textwrap-unicode-linebreak",
  "pretty",
  "std",
  "terminal_size"
]
textwrap-unicode-width = [
  "arbor/textwrap-unicode-width",
  "pretty",
  "std",
  "terminal_size"
]
