# This File is automatically synchronized from https://github.com/Glatzel/template

name: cargo test
description: cargo test

inputs:
  working-directory:
    description: "working-directory"
    default: .
  args:
    description: "args"
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - shell: pwsh
      working-directory: ${{ inputs.working-directory }}
      run: |
        if (Test-Path ./scripts/setup.ps1) { . ./scripts/setup.ps1 }
        pixi global install -c https://prefix.dev/glatzel cargo-llvm-cov cargo-nextest

        Write-Output "::group::nextest"
        cargo +nightly llvm-cov nextest --no-report --branch --no-fail-fast ${{inputs.args}}
        $code = $LASTEXITCODE
        Write-Output "::endgroup::"

        Write-Output "::group::examples"
        cargo +nightly llvm-cov nextest --no-report --branch --no-fail-fast --examples --no-tests pass ${{inputs.args}}
        $code = $code + $LASTEXITCODE
        Write-Output "::endgroup::"

        Write-Output "::group::doctest"
        cargo +nightly llvm-cov --no-report --branch --no-fail-fast --doc ${{inputs.args}}
        $code = $code + $LASTEXITCODE
        Write-Output "::endgroup::"

        Write-Output "::group::report"
        cargo +nightly llvm-cov report
        cargo +nightly llvm-cov report --lcov --output-path lcov.info
        Write-Output "::endgroup::"

        Write-Output "::group::result"
        $code = $code + $LASTEXITCODE
        if ($code -ne 0) {
            Write-Host "Test failed." -ForegroundColor Red
        }
        else {
            Write-Host "Test succeeded." -ForegroundColor Green
        }
        Write-Output "::endgroup::"
        exit $code
    - name: Upload results to Codecov
      if: ${{ !cancelled() }}
      uses: codecov/codecov-action@v5

    - name: Upload test results to Codecov
      if: ${{ !cancelled() }}
      uses: codecov/codecov-action@v5
      with:
        report_type: test_results
        fail_ci_if_error: true
