pub fn hz_to_note() { todo!() }
pub fn hz_to_midi() { todo!() }
pub fn hz_to_svara_h() { todo!() }
pub fn hz_to_svara_c() { todo!() }
pub fn hz_to_fjs() { todo!() }
pub fn midi_to_hz() { todo!() }
pub fn midi_to_note() { todo!() }
pub fn midi_to_svara_h() { todo!() }
pub fn midi_to_svara_c() { todo!() }
pub fn note_to_hz() { todo!() }
pub fn note_to_midi() { todo!() }
pub fn note_to_svara_h() { todo!() }
pub fn note_to_svara_c() { todo!() }
pub fn hz_to_mel() { todo!() }
pub fn hz_to_octs() { todo!() }
pub fn mel_to_hz() { todo!() }
pub fn octs_to_hz() { todo!() }
pub fn a4_to_tuning() { todo!() }
pub fn tuning_to_a4() { todo!() }
