fn _frames_to_samples() { todo!() }
fn _frames_to_time() { todo!() }
fn _samples_to_frames() { todo!() }
fn _samples_to_time() { todo!() }
fn _time_to_frames() { todo!() }
fn _time_to_samples() { todo!() }
fn _blocks_to_frames() { todo!() }
fn _blocks_to_samples() { todo!() }
fn _blocks_to_time() { todo!() }
fn _samples_like() { todo!() }
fn _times_like() { todo!() }
