name: Benchmark FFT

on:
  workflow_dispatch:
    inputs:
      repository:
        default: smu160/PhastFT
        type: string
      ref:
        type: string
        default: main

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  benchmark:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        option:
          - --bench bench
          - --bench rustfft
          - --bench fftw_conserve_c2c
          - --bench fftw_conserve_r2c_c2r
          - --bench fftw_conserve_r2r
          - --bench fftw_estimate_c2c
          - --bench fftw_estimate_r2c_c2r
          - --bench fftw_estimate_r2r
          - --bench fftw_measure_c2c
          - --bench fftw_measure_r2c_c2r
          - --bench fftw_measure_r2r
          - --bench realfft
          - --bench planner
          - --bench interleave --all-features
          - --bench bit_reversal --all-features
      fail-fast: true

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          repository: ${{ inputs.repository }}
          ref: ${{ inputs.ref }}

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@c18668ad3cf93ea998bef934396af7bb5c839dc7 # v10.2.0

      - name: Benchmark
        run: cargo bench ${{ matrix.option }}

      - name: Upload benchmark
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: benchmark-${{ matrix.target }}
          path: target/criterion
          if-no-files-found: error

  merge:
    needs: benchmark
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          repository: ${{ inputs.repository }}
          ref: ${{ inputs.ref }}

      - name: Download benchmark artifacts
        uses: actions/download-artifact@v8
        with:
          pattern: benchmark-*
          path: target/criterion
          merge-multiple: true

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@c18668ad3cf93ea998bef934396af7bb5c839dc7 # v10.2.0

      - name: Plot
        run: |
          uv run benches/plot_criterion_overlay.py \
            --out-dir target/overlays

      - name: Upload overlays
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a0 # v7.0.1
        with:
          name: benchmark-overlays
          path: target/overlays
          if-no-files-found: error
