name: benchmark

on:
  pull_request:
    types:
      - edited
      - synchronize
      - labeled

  push:
    branches: [main]

permissions: read-all

jobs:
  cargo-bench:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo install cargo-codspeed --locked

      - name: Build the benchmark target(s)
        run: cargo codspeed build -p pyxis
        working-directory: ./rust

      - name: Run the benchmarks
        uses: CodSpeedHQ/action@v3
        with:
          run: cargo codspeed run
          token: ${{ secrets.CODSPEED_TOKEN }}
          working-directory: ./rust
