name: Benchmark FFT
on:
  workflow_dispatch:
    inputs:
      repository:
        default: smu160/PhastFT
        type: string
      ref:
        type: string
        default: main
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true
jobs:
  benchmark:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          repository: ${{inputs.repository}}
          ref: ${{inputs.ref}}
          
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@c18668ad3cf93ea998bef934396af7bb5c839dc7 # v10.2.0
      - name: benchmark
        run: cargo bench --all-features
      - name: plot
        run: uv run benches/plot_criterion_overlay.py --out-dir target/overlays
      - name: upload
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: benchmark
          path: |
            target/criterion
            target/overlays
