name: benchmark

on:
  workflow_dispatch:
  workflow_call:

jobs:
  cargo-bench:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@stable
      - uses: ./.github/actions/rust/cargo-test
        with:
          working-directory: ./rust
          args: -p rax -p rax-nmea
