name: Benchmark FFT

on:
  workflow_dispatch:
    inputs:
      repository:
        default: smu160/PhastFT
        type: string
      ref:
        type: string
        default: main

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  benchmark:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        target:
          - c2c_forward
          - c2c_inverse
          - r2c
          - c2r
          - planner
          - interleave
          - bit_reversal
      fail-fast: true

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          repository: ${{ inputs.repository }}
          ref: ${{ inputs.ref }}

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@c18668ad3cf93ea998bef934396af7bb5c839dc7 # v10.2.0

      - name: Benchmark
        run: |
          cargo bench ${{ matrix.target }} --all-features --profile bench
  
      - name: Plot
        run: |
          uv run benches/plot_criterion_overlay.py \
            --out-dir target/overlays

      - name: Upload benchmark
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: benchmark-${{ matrix.target }}
          path: |
            target/criterion
            target/overlays
          if-no-files-found: error
