# This File is automatically synchronized from https://github.com/Glatzel/template

name: update-changelog

on:
  workflow_dispatch:
  release:
    types: [released]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  pull-requests: write

jobs:
  update-changelog:
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
          ref: main
          persist-credentials: false
      - name: Set up pixi
        uses: prefix-dev/setup-pixi@a0af7a228712d6121d37aba47adf55c1332c9c2e # v0.9.4
        with:
          run-install: false

      - run: pixi global install git-cliff

      - run: git-cliff -o CHANGELOG.md

      - name: Create pull request
        uses: peter-evans/create-pull-request@c0f553fe549906ede9cf27b5156039d195d2ece0 # v8.1.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: update changelog.md"
          title: "chore: update changelog.md"
          branch: update-changelog
          base: main
          delete-branch: true
          add-paths: CHANGELOG.md
          assignees: Glatzel
          draft: false
