# This File is automatically synchronized from https://github.com/Glatzel/template

name: Update Changelog

on:
  workflow_dispatch:
  release:
    types: [released]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  pull-requests: write

jobs:
  update-changelog:
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
          ref: main
      - name: Set up pixi
        uses: prefix-dev/setup-pixi@a0af7a228712d6121d37aba47adf55c1332c9c2e # v0.9.4
        with:
          run-install: false

      - name: Create pull request
        shell: pwsh
        run: |
          git checkout -b "update-changelog"
          pixi global install git-cliff
          git-cliff -o CHANGELOG.md
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          if (-not (git diff --cached --quiet)) {
              git commit -m "chore: update changelog.md"
              git push -u origin update-changelog --force-with-lease
          } else {
              echo "No changes to commit"
              exit 0
          }
          gh pr create `
            --title "chore: update changelog.md" `
            --body "" `
            --base main `
            --head update-changelog
        env:
          GH_TOKEN: ${{ github.token }}
