# This File is automatically synchronized from https://github.com/Glatzel/template

name: Lefthook

on:
  workflow_dispatch:
  workflow_call:
permissions:
  contents: write
  pull-requests: write
jobs:
  lefthook:
    runs-on: ubuntu-latest
    steps:
      - uses: Glatzel/template/.github/actions/common/lefthook@e5b6ee4c6d9ddb2d5e329fc7d338b1787e40d204 # v2026.8.24
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
