# This File is automatically synchronized from https://github.com/Glatzel/template

name: lefthook

on:
  workflow_dispatch:
  workflow_call:
permissions:
  contents: write
jobs:
  lefthook:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ref: ${{ github.head_ref }}
      - uses: actions/cache@668228422ae6a00e4ad889ee87cd7109ec5666a7 # v5.0.4
        with:
          path: |
            ./lefthook/.pixi
          key: lefthook-${{ hashFiles('lefthook.yaml','./lefthook/pixi*')}}
          restore-keys: |
            lefthook

      #  pixi setup
      - name: Set up pixi
        uses: prefix-dev/setup-pixi@a0af7a228712d6121d37aba47adf55c1332c9c2e # v0.9.4
        with:
          run-install: false

      # pre-commit
      - name: lefthook
        run: pixi run --manifest-path ./lefthook/pixi.toml lefthook-run

      - name: Auto commit fixes
        if: ${{ !cancelled() && startsWith(github.ref, 'refs/pull/') && github.actor != 'github-actions[bot]' }}
        shell: pwsh
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          if (-not (git diff --cached --quiet)) {
              git commit -m "apply lefthook fixes"
              git push
          } else {
              echo "No changes to commit"
          }
