name: python-CI

on:
  workflow_dispatch:
  workflow_call:
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - parallel:
        - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        - name: Set up pixi
          uses: prefix-dev/setup-pixi@f00437f565399d418b0acc85936d12c1fb668347 # v0.10.1
          with:
            run-install: false
      - uses: Glatzel/template/.github/actions/python/pytest@12f2e09e2f6e0eb8a65962709e52ab596e672732 # v2026.8.28
        with:
          working-directory: ./python
        env:
          PYTHONPATH: ./src
      - uses: Glatzel/template/.github/actions/common/codecov@12f2e09e2f6e0eb8a65962709e52ab596e672732 # v2026.8.28
        if: ${{!cancelled()}}
        with:
          flags: ci-python
