name: python-CI

on:
  workflow_dispatch:
  workflow_call:
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - name: Set up pixi
        uses: prefix-dev/setup-pixi@5185adfbffb4bd703da3010310260805d89ebb11 # v0.9.6
        with:
          run-install: false
      - uses: ./.github/actions/python/pytest
        with:
          working-directory: ./python
        env:
          PYTHONPATH: ./src
      - uses: ./.github/actions/common/codecov
        if: ${{!cancelled()}}
