name: python-CI

on:
  workflow_dispatch:
  workflow_call:

permissions: read-all
env:
  PYTHON_ROOT: ${{github.workspace}}/python
jobs:
  rattler:
    env:
      PYTEST_ADDOPTS: "--color=yes"
    strategy:
      fail-fast: false
      matrix:
        machine: [windows-latest, ubuntu-latest, macos-latest]
    runs-on: ${{matrix.machine}}
    steps:
      - uses: actions/checkout@v4
      - name: Set up pixi
        uses: prefix-dev/setup-pixi@v0.8.14
        with:
          run-install: false

      - name: test
        run: ${{env.PYTHON_ROOT}}/scripts/pytest.ps1
        shell: pwsh

      - name: Upload results to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/codecov-action@v5
      - name: Upload test results to Codecov
        if: ${{ !cancelled()}}
        uses: codecov/test-results-action@v1
        with:
          fail_ci_if_error: true
