name: python-CI

on:
  workflow_dispatch:
  workflow_call:
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - parallel:
        - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        - name: Set up pixi
          uses: prefix-dev/setup-pixi@d3f436a425481402e6a95a1d1fc10331c708cd9e # v0.10.2
          with:
            run-install: false
      - uses: Glatzel/template/.github/actions/python/pytest@ad33a0f240851891ccb1498fa5d520aafbec454d # v2026.9.11
        with:
          working-directory: ./python
        env:
          PYTHONPATH: ./src
      - uses: Glatzel/template/.github/actions/common/codecov@ad33a0f240851891ccb1498fa5d520aafbec454d # v2026.9.11
        if: ${{!cancelled()}}
        with:
          flags: ci-python
