name: rust-CI

on:
  workflow_dispatch:
  workflow_call:
permissions: read-all
defaults:
  run:
    working-directory: ./rust
env:
  WORKDIR: ./rust
jobs:
  cargo-test:
    strategy:
      fail-fast: false
      matrix:
        args:
          - --workspace --all-features --exclude clerk
          - -p mischief --no-default-features --features macros
          - --features tracing -p clerk
          - --no-default-features -p rax -p rax-nmea
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: ./.github/actions/rust/setup-rust
        with:
          toolchain: nightly
      - uses: ./.github/actions/rust/cargo-clippy
        with:
          working-directory: ${{env.WORKDIR}}
          args: ${{matrix.args}}
      - uses: ./.github/actions/rust/cargo-test
        with:
          working-directory: ${{env.WORKDIR}}
          args: ${{matrix.args}}

  cargo-miri:
    strategy:
      fail-fast: false
      matrix:
        machine: [ubuntu-latest]
    runs-on: ${{matrix.machine}}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: ./.github/actions/rust/setup-rust
        with:
          toolchain: nightly
          components: "miri"
      - uses: ./.github/actions/rust/cargo-miri
        with:
          working-directory: ${{env.WORKDIR}}
          args: -p envoy
  cargo-doc:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        args:
          - --workspace --all-features --exclude clerk
          - --features tracing -p clerk
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: ./.github/actions/rust/setup-rust
      - uses: ./.github/actions/rust/cargo-test
        with:
          working-directory: ${{env.WORKDIR}}
          args: ${{matrix.args}}
