name: rust-CI

on:
  workflow_dispatch:
  workflow_call:
defaults:
  run:
    working-directory: ./rust
env:
  WORKDIR: ./rust
jobs:
  cargo-test:
    strategy:
      fail-fast: false
      matrix:
        options:
          - --workspace --all-features --exclude clerk --exclude mischief
          - -p mischief --no-default-features --features macros,fancy
          - -p mischief --no-default-features --features macros
          - -p clerk --features tracing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: ./.github/actions/rust/setup-rust
        with:
          toolchain: nightly
          components: clippy
      - uses: ./.github/actions/rust/cargo-clippy
        with:
          working-directory: ${{env.WORKDIR}}
          options: ${{matrix.options}}
          args: -D warnings
      - uses: ./.github/actions/rust/cargo-test
        with:
          working-directory: ${{env.WORKDIR}}
          global-options: ${{matrix.options}}
      - uses: ./.github/actions/common/codecov
        if: ${{!cancelled()}}

  cargo-miri:
    strategy:
      fail-fast: false
      matrix:
        machine: [ubuntu-latest]
    runs-on: ${{matrix.machine}}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: ./.github/actions/rust/setup-rust
        with:
          toolchain: nightly
          components: "miri"
      - uses: ./.github/actions/rust/cargo-miri
        with:
          working-directory: ${{env.WORKDIR}}
          options: -p envoy

  cargo-doc:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        options:
          - --workspace --all-features --exclude clerk
          - --features tracing -p clerk
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: ./.github/actions/rust/setup-rust
      - uses: ./.github/actions/rust/cargo-doc
        with:
          working-directory: ${{env.WORKDIR}}
          options: ${{matrix.options}}
