name: CI

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      release:
        type: boolean
        default: false
  push:
    branches: [main]
  pull_request:
    types:
      - opened
      - synchronize
      - ready_for_review
  schedule:
    - cron: 0 16 * * *

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lefthook:
    if: ${{ github.event_name != 'schedule' }}
    uses: ./.github/workflows/ci-lefthook.yml
    permissions:
      contents: write
  changed:
    outputs:
      changed-benchmark: ${{ steps.main.outputs.benchmark_any_changed }}
      changed-python: ${{ steps.main.outputs.python_any_changed }}
      changed-rust: ${{ steps.main.outputs.rust_any_changed }}

      changed-tools-orc: ${{ steps.main.outputs.tools-orc_any_changed }}
      changed-tools-vinaya: ${{ steps.main.outputs.tools-vinaya_any_changed }}
    runs-on: ubuntu-slim
    steps:
      - if: ${{github.event_name == 'pull_request' }}
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - id: main
        if: ${{github.event_name == 'pull_request' }}
        uses: tj-actions/changed-files@24d32ffd492484c1d75e0c0b894501ddb9d30d62 # v47.0.0
        with:
          files_yaml: |
            benchmark:
              - ./rust/crates/rax/**
              - ./.github/workflows/benchmark.yml
            python:
              - ./python/**
              - ./.github/workflows/ci-python.yml
            rust:
              - ./rust/**
              - ./.github/actions/rust/**
              - ./.github/workflows/ci-rust.yml

            tools-orc:
              - ./.github/actions/rust/**
              - ./tools/orc/**
            tools-vinaya:
              - ./.github/actions/rust/**
              - ./tools/vinaya/**
  benchmark:
    needs: changed
    if: ${{ needs.changed.outputs.changed-benchmark != 'false' }}
    uses: ./.github/workflows/benchmark.yml
  python-ci:
    needs: changed
    if: ${{ needs.changed.outputs.changed-python != 'false' }}
    uses: ./.github/workflows/ci-python.yml
  rust-ci:
    needs: changed
    if: ${{ needs.changed.outputs.changed-rust != 'false' }}
    uses: ./.github/workflows/ci-rust.yml

  tools-orc:
    needs: changed
    if: ${{ needs.changed.outputs.changed-tools-orc != 'false' }}
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: ./.github/actions/rust/setup-rust
      - uses: ./.github/actions/rust/cargo-clippy
        with:
          working-directory: ./tools/orc
      - uses: ./.github/actions/rust/cargo-build
        with:
          working-directory: ./tools/orc

  tools-vinaya:
    needs: changed
    if: ${{ needs.changed.outputs.changed-tools-vinaya != 'false' }}
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: ./.github/actions/rust/setup-rust
      - uses: ./.github/actions/rust/cargo-clippy
        with:
          working-directory: ./tools/vinaya
      - uses: ./.github/actions/rust/cargo-test
        with:
          working-directory: ./tools/vinaya
          skip-doc: true

  check-point:
    if: ( cancelled() || failure() ) && github.event_name == 'pull_request'
    needs: [lefthook, changed, python-ci, rust-ci, benchmark, tools-orc]
    runs-on: ubuntu-slim
    steps:
      - run: exit 1
