name: CI

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      release:
        type: boolean
        default: false
  push:
    branches: [main]
  pull_request:
    types:
      - opened
      - synchronize
      - ready_for_review
  schedule:
    - cron: 0 16 * * *

permissions: read-all

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name != 'push'}}

jobs:
  lefthook:
    if: ${{ github.event_name != 'schedule' }}
    uses: ./.github/workflows/ci-lefthook.yml
    with:
      cache-rust: true
  changed:
    outputs:
      changed-benchmark: ${{ steps.main.outputs.benchmark_any_changed }}
      changed-python: ${{ steps.main.outputs.python_any_changed }}
      changed-rust: ${{ steps.main.outputs.rust_any_changed }}
    runs-on: ubuntu-slim
    steps:
      - if: ${{github.event_name == 'pull_request'}}
        uses: actions/checkout@v6
      - id: main
        if: ${{github.event_name == 'pull_request'}}
        uses: tj-actions/changed-files@v47
        with:
          files_yaml: |
            benchmark:
              - ./rust/**
              - ./.github/workflows/benchmark.yml
            python:
              - ./python/**
              - ./.github/workflows/ci-python.yml
            rust:
              - ./rust/**
              - ./.github/workflows/ci-rust.yml

  python-ci:
    needs: changed
    if: ${{ needs.changed.outputs.changed-python != 'false' }}
    uses: ./.github/workflows/ci-python.yml

  rust-ci:
    needs: changed
    if: ${{ needs.changed.outputs.changed-rust != 'false' }}
    uses: ./.github/workflows/ci-rust.yml
  benchmark:
    needs: changed
    if: ${{ needs.changed.outputs.changed-benchmark != 'false' }}
    uses: ./.github/workflows/benchmark.yml
  check-point:
    if: ( cancelled() || failure() ) && github.event_name == 'pull_request'
    needs: [lefthook,changed,python-ci,rust-ci,benchmark]
    runs-on: ubuntu-slim
    steps:
      - run: exit 1
