name: CI

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    types:
      - opened
      - synchronize
      - ready_for_review
  schedule:
    - cron: 0 16 * * *

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lefthook:
    if: ${{ github.event_name != 'schedule' }}
    uses: ./.github/workflows/ci-lefthook.yml
    permissions:
      contents: write
      pull-requests: write
  changed:
    outputs:
      changed-benchmark: ${{ steps.main.outputs.benchmark_any_changed }}
      changed-python: ${{ steps.main.outputs.python_any_changed }}
      changed-rust: ${{ steps.main.outputs.rust_any_changed }}

      changed-tools-orc: ${{ steps.main.outputs.tools-orc_any_changed }}
      changed-tools-ttyw: ${{ steps.main.outputs.tools-ttyw_any_changed }}
      changed-tools-vinaya: ${{ steps.main.outputs.tools-vinaya_any_changed }}
    runs-on: ubuntu-slim
    steps:
      - if: ${{github.event_name == 'pull_request'}}
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - id: main
        if: ${{github.event_name == 'pull_request'}}
        uses: tj-actions/changed-files@9426d40962ed5378910ee2e21d5f8c6fcbf2dd96 # v47.0.6
        with:
          files_yaml: |
            benchmark:
              - ./rust/crates/rax/**
              - ./.github/workflows/benchmark.yml
            python:
              - ./python/**
              - ./.github/actions/python/**
              - ./.github/workflows/ci-python.yml
            rust:
              - ./rust/**
              - ./.github/actions/rust/**
              - ./.github/workflows/ci-rust.yml

            tools-orc:
              - ./.github/actions/rust/**
              - ./tools/orc/**
            tools-ttyw:
              - ./.github/actions/rust/**
              - ./tools/ttyw/**
            tools-vinaya:
              - ./.github/actions/rust/**
              - ./tools/vinaya/**
  benchmark:
    needs: changed
    if: ${{ needs.changed.outputs.changed-benchmark != 'false' }}
    uses: ./.github/workflows/benchmark.yml
  python-ci:
    needs: changed
    if: ${{ needs.changed.outputs.changed-python != 'false' }}
    uses: ./.github/workflows/ci-python.yml
  rust-ci:
    needs: changed
    if: ${{ needs.changed.outputs.changed-rust != 'false' }}
    uses: ./.github/workflows/ci-rust.yml

  tools-orc:
    needs: changed
    if: ${{ needs.changed.outputs.changed-tools-orc != 'false' }}
    strategy:
      fail-fast: false
      matrix:
        machine: [windows-latest, ubuntu-latest]
    runs-on: ${{ matrix.machine }}
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: ./.github/actions/rust/setup-rust
        with:
          toolchain: nightly
          components: clippy
      - uses: ./.github/actions/rust/cargo-clippy
        with:
          working-directory: ./tools/orc
        background: true
      - uses: ./.github/actions/rust/cargo-test
        with:
          working-directory: ./tools/orc
          nextest-options: --all-features --dep-coverage arbor,clap-style,clerk,mischief
          doc: false
      - uses: ./.github/actions/common/codecov
        if: ${{!cancelled()}}

  tools-ttyw:
    needs: changed
    if: ${{ needs.changed.outputs.changed-tools-ttyw != 'false' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Set up pixi
        uses: prefix-dev/setup-pixi@a09b6247153796b190642a2b53fac4241043cf6f # v0.10.0
        with:
          run-install: false
      - name: frontend
        run: |
          pixi run install
          pixi run check
          pixi run build
        working-directory: ./tools/ttyw
      - uses: ./.github/actions/rust/setup-rust
        with:
          toolchain: nightly
          components: clippy
      - uses: ./.github/actions/rust/cargo-clippy
        with:
          working-directory: ./tools/ttyw
        background: true
      - uses: ./.github/actions/rust/cargo-test
        with:
          working-directory: ./tools/ttyw
          doc: false
          nextest-options: --all-features --dep-coverage clap-style,clerk,mischief
      - uses: ./.github/actions/common/codecov
        if: ${{!cancelled()}}

  tools-vinaya:
    needs: changed
    if: ${{ needs.changed.outputs.changed-tools-vinaya != 'false' }}
    strategy:
      fail-fast: false
      matrix:
        machine: [windows-latest, macos-latest, ubuntu-latest]
    runs-on: ${{matrix.machine}}
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: ./.github/actions/rust/setup-rust
        with:
          toolchain: nightly
          components: clippy
      - uses: ./.github/actions/rust/cargo-clippy
        if: ${{matrix.machine=='ubuntu-latest'}}
        with:
          working-directory: ./tools/vinaya
        background: true
      - uses: ./.github/actions/rust/cargo-test
        with:
          working-directory: ./tools/vinaya
          doc: false
          nextest-options: --all-features --dep-coverage clap-style,clerk,mischief
      - uses: ./.github/actions/common/codecov
        if: ${{!cancelled()}}

  fuzz:
    if: github.event_name == 'workflow_dispatch' || github.event_name == 'schedule'
    uses: ./.github/workflows/fuzz.yml

  check-point:
    if: ( cancelled() || failure() ) && github.event_name == 'pull_request'
    needs:
      [
        fuzz,
        benchmark,
        changed,
        lefthook,
        python-ci,
        rust-ci,
        tools-orc,
        tools-ttyw,
        tools-vinaya,
      ]
    runs-on: ubuntu-slim
    steps:
      - run: exit 1
