name: fuzz
on:
  workflow_dispatch:
  workflow_call:
jobs:
  fuzz:
    if: github.event_name == 'workflow_dispatch' || github.event_name == 'schedule'
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: fuzz-rax
            pwd: ./fuzz/fuzz-rax
          - target: fuzz-rax-nmea
            pwd: ./fuzz/fuzz-rax-nmea

    runs-on: ubuntu-latest
    steps:
      - parallel:
          - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
          - uses: Glatzel/template/.github/actions/rust/setup-rust# v2026.8.16
            with:
              toolchain: nightly
              components: llvm-tools-preview
      - uses: Glatzel/template/.github/actions/rust/cargo-fuzz# v2026.8.16
        with:
          working-directory: ${{matrix.pwd}}
          target: ${{matrix.target}}
      - uses: Glatzel/template/.github/actions/common/codecov# v2026.8.16
        if: ${{!cancelled()}}
        with:
          flags: ${{matrix.target}}
