name: fuzz
on:
  workflow_dispatch:
  workflow_call:
jobs:
  fuzz:
    if: github.event_name == 'workflow_dispatch' || github.event_name == 'schedule'
    strategy:
      fail-fast: false
      matrix:
        target: [fuzz-rax, fuzz-rax-nmea]
        include:
          - target: fuzz-rax
            pwd: ./fuzz/fuzz-rax
          - target: fuzz-rax-nmea
            pwd: ./fuzz/fuzz-rax-nmea

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: ./.github/actions/rust/setup-rust
        with:
          toolchain: nightly
          components: llvm-tools-preview
      - uses: ./.github/actions/rust/cargo-fuzz
        with:
          working-directory: ${{matrix.pwd}}
          target: ${{matrix.target}}
      - uses: ./.github/actions/common/codecov
        if: ${{!cancelled()}}
        with:
          flags: fuzz
