name: post-release

on:
  workflow_dispatch:

  release:
    types: [released]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  pull-requests: write
  id-token: write
jobs:
  update-changelog:
    uses: Glatzel/template/.github/workflows/changelog.yml@main
  upload-prefix:
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: Glatzel/template/.github/workflows/upload-prefix.yml@main
