name: post-release

on:
  workflow_dispatch:

  release:
    types: [released]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  pull-requests: write

jobs:
  update-changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up pixi
        uses: prefix-dev/setup-pixi@v0.8.12
        with:
          run-install: false

      - run: pixi global install git-cliff

      - run: git-cliff > changelog.md

      - name: Create pull request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: update changelog.md"
          title: "chore: update changelog.md"
          branch: update-changelog
          base: main
          labels: action
          delete-branch: true
          add-paths: changelog.md
          assignees: Glatzel
          draft: false

  upload-conda:
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Set up pixi
        uses: prefix-dev/setup-pixi@v0.8.12
        with:
          run-install: false

      - run: pixi global install rattler-build

      - name: download
        env:
          GH_TOKEN: ${{ github.token }}
        run: gh release download -R Glatzel/toolbox -p "*.conda"

      - name: upload
        run: |
            foreach ($pkg_file in Get-ChildItem "./*.conda") {
              Write-Output "::group:: upload $pkg_file"
              rattler-build upload prefix -c glatzel $pkg_file
              Write-Output "::endgroup::"
            }
        shell: pwsh
