# This File is automatically synchronized from https://github.com/Glatzel/template

name: release

on:
  workflow_dispatch:
    inputs:
      tag:
        type: string
        required: true
        description: "Tag to release (e.g., v1.2.3)"
      latest:
        type: boolean
        required: false
        default: true
        description: is it a latest release

permissions:
  contents: write

jobs:
  create-release:
    if: ${{!failure()}}
    runs-on: ubuntu-slim
    steps:
      - name: check-tag-release
        if: inputs.latest
        run: |
          Write-Output "tag: $tag"
          if("${{inputs.tag}}" -match '^v\d+\.\d+\.\d+$' ){}
          else{throw "Unknown version: '${{inputs.tag}}'"}
        shell: pwsh
        env:
          INPUTS_TAG: ${{inputs.tag}}
      - name: check-tag-pre-release
        if: ! inputs.latest
        run: |
          Write-Output "tag: ${{inputs.tag}}"
          if("$tag" -match '^v\d+\.\d+\.\d+-.*$') {}
          else{throw "Unknown version: '${{inputs.tag}}'"}
        shell: pwsh
        env:
          INPUTS_TAG: ${{inputs.tag}}

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: clear-tag-and-release
        run: |
          if($(gh api /repos/${{github.repository}}/tags --jq '.[].name') -contains "${{inputs.tag}}")
          {
              write-output "tag $env:INPUTS_TAG exists."
              gh release delete $env:INPUTS_TAG --cleanup-tag -y
          }
          else{
              write-output "tag $env:INPUTS_TAG does not exist."
          }
        env:
          GH_TOKEN: ${{ github.token }}
        shell: pwsh

      - name: Set up pixi
        uses: prefix-dev/setup-pixi@a0af7a228712d6121d37aba47adf55c1332c9c2e # v0.9.4
        with:
          run-install: false

      - name: Generate a changelog
        run: |
          pixi global install git-cliff
          git-cliff --unreleased --tag ${{inputs.tag}} --strip header > release_changelog.md

      - name: Release
        run: gh release create ${{inputs.tag}} -F release_changelog.md --draft ${{inputs.latest && '--latest' || '--prerelease'}}
