# This File is automatically synchronized from https://github.com/Glatzel/template

name: upload-prefix

on:
  workflow_dispatch:
  release:
    types: [released]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  id-token: write
jobs:
  upload-prefix:
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Set up pixi
        uses: prefix-dev/setup-pixi@v0.9.1
        with:
          run-install: false

      - run: pixi global install rattler-build
        shell: pwsh

      - name: Download Conda Packages
        env:
          GH_TOKEN: ${{ github.token }}
        run: gh release download -R ${{ github.repository }} -p "*.conda"
        shell: pwsh

      - name: Upload Conda Packages
        shell: pwsh
        run: |
          foreach ($pkg_file in Get-ChildItem "./*.conda") {
            Write-Output "::group::upload $pkg_file"
            rattler-build upload prefix -c glatzel $pkg_file
            Write-Output "::endgroup::"
          }
