[devop]
vendor = "github"
token = "token_xxxxx"
webhook_secret = "webhook_secret_xxxxxxx"
allowed_repositories = ["self-host-runner"]
allowed_users = ["Glatzel"]

[kioyu]
memory = 8192

[runners]
[runners.ghar-linux-dev-small]
image = "ghcr.io/glatzel/ghar-linux-dev"
cpus = 1
memory = 512
envs = { EPHEMERAL = "true", RUNNER_LABELS = "self-hosted,ghar-linux-dev-small" }
